In [2]:
from tensorflow.keras.preprocessing.text import one_hot


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[399, 4451, 827, 1570],
 [399, 4451, 827, 5913],
 [399, 6168, 827, 5311],
 [5694, 7063, 8472, 1705, 4299],
 [5694, 7063, 8472, 1705, 9484],
 [7488, 399, 7307, 827, 1380],
 [3327, 8582, 8344, 1705]]

In [17]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  399 4451  827 1570]
 [   0    0    0    0  399 4451  827 5913]
 [   0    0    0    0  399 6168  827 5311]
 [   0    0    0 5694 7063 8472 1705 4299]
 [   0    0    0 5694 7063 8472 1705 9484]
 [   0    0    0 7488  399 7307  827 1380]
 [   0    0    0    0 3327 8582 8344 1705]]


In [11]:
dim=10

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential()

model.add(Input(shape=(20,)))
model.add(Embedding(voc_size, dim))

model.compile(optimizer='adam', loss='mse')

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 20, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step


array([[[ 6.72291964e-04, -7.44115189e-03,  2.78689526e-02,
          2.63543241e-02, -9.30697843e-03, -3.45099680e-02,
         -4.76295352e-02, -4.17454615e-02, -3.82853262e-02,
         -4.78096716e-02],
        [ 6.72291964e-04, -7.44115189e-03,  2.78689526e-02,
          2.63543241e-02, -9.30697843e-03, -3.45099680e-02,
         -4.76295352e-02, -4.17454615e-02, -3.82853262e-02,
         -4.78096716e-02],
        [ 6.72291964e-04, -7.44115189e-03,  2.78689526e-02,
          2.63543241e-02, -9.30697843e-03, -3.45099680e-02,
         -4.76295352e-02, -4.17454615e-02, -3.82853262e-02,
         -4.78096716e-02],
        [ 6.72291964e-04, -7.44115189e-03,  2.78689526e-02,
          2.63543241e-02, -9.30697843e-03, -3.45099680e-02,
         -4.76295352e-02, -4.17454615e-02, -3.82853262e-02,
         -4.78096716e-02],
        [ 3.97934429e-02, -3.09327990e-03,  3.47801484e-02,
          2.74738781e-02,  1.98119767e-02, -1.11498609e-02,
         -4.42106612e-02,  4.29529436e-02, -8.550953